version: "3.7"

services:
  web:
    build: .
    depends_on:
      - kubo
    ports:
      - 8765:8765
    restart: on-failure
    user: 1000:1000
    volumes:
      - ${PWD}/cfg:/ipfs-podcasting/cfg

  kubo:
    image: ipfs/kubo
    ports:
      - 4001:4001  # IPFS
     # - 5001:5001  # private!
      - 8080:8080  # gateway
    restart: on-failure
    user: 1000:1000
    volumes:
      - ${PWD}/data/ipfs:/data/ipfs
